# Generated by Django 6.0.2 on 2026-03-26 08:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('specialization_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Only letters allowed.', regex='^[A-Za-z\\s]+$')])),
            ],
            options={
                'db_table': 'specializations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Indian phone number.', regex='^(\\+91)?[6-9]\\d{9}$')])),
                ('address', models.TextField()),
                ('qualification', models.CharField(max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('doctor_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)])),
                ('max_patient_per_day', models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('is_active', models.BooleanField(default=True)),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='Admin.specialization')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_profile', to='Admin.staff')),
            ],
            options={
                'db_table': 'doctor_profiles',
                'ordering': ['doctor_code'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='Admin.doctorprofile')),
            ],
            options={
                'db_table': 'doctor_schedule',
                'ordering': ['doctor', 'day_of_week', 'start_time'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('doctor', 'day_of_week', 'start_time', 'end_time'), name='unique_active_schedule')],
            },
        ),
    ]
