# Generated by Django 6.0.2 on 2026-03-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/'),
        ),
    ]
