# Generated by Django 6.0.2 on 2026-03-30 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_doctorprofile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='profile_image',
        ),
    ]
