# Generated by Django 6.0.2 on 2026-03-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'Booked'), ('IN_PROGRESS', 'In Progress'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='BOOKED', max_length=15),
        ),
    ]
