# Generated by Django 6.0.2 on 2026-04-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_doctorprofile_profile_image'),
        ('Receptionist', '0005_alter_appointment_status_alter_patient_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='slot_time',
            field=models.TimeField(blank=True, help_text='The specific 20-minute slot start time assigned to this patient.', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_code',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('slot_time__isnull', False)), fields=('schedule', 'appointment_date', 'slot_time'), name='unique_slot_per_schedule_date'),
        ),
    ]
