# Generated by Django 6.0.2 on 2026-03-26 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Doctor', '0001_initial'),
        ('Pharmacist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineprescription',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Pharmacist.medicine'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='consultation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='Doctor.consultation'),
        ),
        migrations.AddField(
            model_name='medicineprescription',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='Doctor.prescription'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['appointment'], name='Doctor_cons_appoint_ff295a_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['consultation'], name='Doctor_pres_consult_c24372_idx'),
        ),
        migrations.AddIndex(
            model_name='medicineprescription',
            index=models.Index(fields=['prescription'], name='Doctor_medi_prescri_cab4a4_idx'),
        ),
        migrations.AddIndex(
            model_name='medicineprescription',
            index=models.Index(fields=['medicine'], name='Doctor_medi_medicin_1c7aab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='medicineprescription',
            unique_together={('prescription', 'medicine')},
        ),
    ]
