# Generated by Django 6.0.2 on 2026-04-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineprescription',
            name='buy_outside_clinic',
            field=models.BooleanField(default=False, help_text='Doctor has indicated patient should purchase this medicine outside the clinic.'),
        ),
        migrations.AddField(
            model_name='medicineprescription',
            name='is_low_stock',
            field=models.BooleanField(default=False),
        ),
        # # migrations.AlterField(
        #     model_name='medicineprescription',
        #     name='frequency',
        #     field=models.CharField(max_length=20),
        # ),
    ]
